export const TRUN = {
  DATA_OFFSET_PRESENT : 0x1,
  FIRST_SAMPLE_FLAG_PRESENT : 0x4,
  SAMPLE_DURATION_PRESENT : 0x100,
  SAMPLE_SIZE_PRESENT : 0x200,
  SAMPLE_FLAG_PRESENT : 0x400,
  SAMPLE_CTTS_PRESENT : 0x800,
  ENTRIES_KEYFRAME : 1 << 25,
  ENTRIES_NON_KEYFRAME : 1 << 16
}

export const TFHD = {
  BASE_DATA_OFFSET_PRESENT : 0x1,
  SAMPLE_DESCRIPTION_INDEX_PRESENT : 0x2,
  SAMPLE_DURATION_PRESENT : 0x8,
  SAMPLE_SIZE_PRESENT : 0x10,
  SAMPLE_FLAG_PRESENT : 0x20,
  DURATION_IS_EMPTY : 0x10000,
  DEFAULT_BASE_IS_MOOF : 0x20000
}

